version: "3.7"
services:
  go-yts:
    image: hibare/go-yts
    container_name: go-yts
    hostname: go-yts
    restart: always
    environment:
      - GO_YTS_SCHEDULE=0 */4 * * *
      - GO_YTS_DATA_DIR=/data
    volumes:
        - go-yts:/data
volumes:
  go-yts: